import React, { useState, useContext } from "react";
import { AppContext } from "../context/AppContext";
import {
  Utensils, Zap, Scale, Clock, ChevronRight,
  Apple, Droplets, AlertTriangle, CheckCircle, Coffee
} from "lucide-react";
import axios from "axios";
import { toast } from "react-toastify";

const Nutrition = () => {
  const { backendUrl, token } = useContext(AppContext);

  const [age, setAge] = useState("");
  const [weight, setWeight] = useState("");
  const [conditions, setConditions] = useState("");
  const [activityLevel, setActivityLevel] = useState("");
  const [dietPlan, setDietPlan] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!token) return toast.error("Please login to generate a plan");

    setLoading(true);
    try {
      const { data } = await axios.post(
        `${backendUrl}/api/user/diet-plan`,
        { age, weight, conditions, activityLevel },
        { headers: { token } }
      );

      if (data.success) {
        setDietPlan(data.plan);
        toast.success("HeartFlow nutrition plan generated!");
      } else {
        toast.error(data.message);
      }
    } catch (error) {
      toast.error("Error connecting to HeartFlow services");
    } finally {
      setLoading(false);
    }
  };

  const meals = dietPlan
    ? [
        {
          label: "Breakfast",
          sublabel: "Morning Fuel",
          data: dietPlan.breakfast,
          icon: <Coffee size={20} />,
          dark: false,
        },
        {
          label: "Morning Snack",
          sublabel: "Mid-Morning Boost",
          data: dietPlan.morningSnack,
          icon: <Apple size={20} />,
          dark: false,
        },
        {
          label: "Lunch",
          sublabel: "Core Performance",
          data: dietPlan.lunch,
          icon: <Zap size={20} />,
          dark: false,
        },
        {
          label: "Afternoon Snack",
          sublabel: "Energy Top-Up",
          data: dietPlan.afternoonSnack,
          icon: <Clock size={20} />,
          dark: false,
        },
        {
          label: "Dinner",
          sublabel: "Restorative Fuel",
          data: dietPlan.dinner,
          icon: <Scale size={20} />,
          dark: true,
        },
        {
          label: "Hydration",
          sublabel: "Daily Fluid Intake",
          data: dietPlan.hydration,
          icon: <Droplets size={20} />,
          dark: false,
        },
      ]
    : [];

  return (
    <div className="p-6 md:p-12 bg-[#FDFDFD] min-h-screen">

      <div className="text-center mb-14">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 mb-4 bg-red-50 border border-red-100 rounded-full">
          <Apple size={14} className="text-red-600" />
          <p className="text-[10px] font-black tracking-[0.3em] text-red-600 uppercase">
            AI-Powered Nutrition
          </p>
        </div>
        <h1 className="text-4xl font-black tracking-tighter uppercase text-slate-900 md:text-6xl">
          Cardio <span className="italic text-red-600">Nutrition</span>
        </h1>
        <p className="max-w-xl mx-auto mt-4 text-sm font-bold tracking-widest uppercase text-slate-400">
          Personalized heart-healthy meal plans generated by clinical AI.
        </p>
      </div>

      <div className="max-w-6xl mx-auto">

        <div className="bg-white shadow-[0_20px_50px_rgba(0,0,0,0.04)] rounded-[3rem] p-10 border border-slate-100 relative overflow-hidden mb-10">
          <div className="absolute top-0 right-0 w-48 h-48 translate-x-24 -translate-y-24 rounded-full bg-red-50 opacity-40" />

          <h2 className="relative z-10 mb-8 text-2xl font-black tracking-tight uppercase text-slate-800">
            Biometric <span className="text-red-600">Profile</span>
          </h2>

          <form onSubmit={handleSubmit} className="relative z-10">
            <div className="grid grid-cols-1 gap-6 mb-6 md:grid-cols-2 lg:grid-cols-4">
              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase ml-1">
                  Age (Years)
                </label>
                <input
                  type="number"
                  value={age}
                  onChange={(e) => setAge(e.target.value)}
                  className="w-full px-5 py-4 font-bold transition-all outline-none bg-slate-50 rounded-2xl focus:ring-2 focus:ring-red-500/20 text-slate-700"
                  placeholder="35"
                  required
                />
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase ml-1">
                  Weight (KG)
                </label>
                <input
                  type="number"
                  value={weight}
                  onChange={(e) => setWeight(e.target.value)}
                  className="w-full px-5 py-4 font-bold transition-all outline-none bg-slate-50 rounded-2xl focus:ring-2 focus:ring-red-500/20 text-slate-700"
                  placeholder="75"
                  required
                />
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase ml-1">
                  Activity Level
                </label>
                <select
                  value={activityLevel}
                  onChange={(e) => setActivityLevel(e.target.value)}
                  className="w-full px-5 py-4 font-bold transition-all outline-none appearance-none bg-slate-50 rounded-2xl focus:ring-2 focus:ring-red-500/20 text-slate-700"
                  required
                >
                  <option value="">Select Level</option>
                  <option value="Sedentary">Sedentary (desk work)</option>
                  <option value="Moderate">Moderate (3–5 days/week)</option>
                  <option value="Active">Active (daily athlete)</option>
                </select>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase ml-1">
                  Medical Conditions
                </label>
                <input
                  type="text"
                  value={conditions}
                  onChange={(e) => setConditions(e.target.value)}
                  className="w-full px-5 py-4 font-bold transition-all outline-none bg-slate-50 rounded-2xl focus:ring-2 focus:ring-red-500/20 text-slate-700"
                  placeholder="e.g. diabetes, hypertension"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="group w-full py-5 bg-red-600 text-white font-black uppercase tracking-[0.2em] rounded-2xl hover:bg-red-700 shadow-xl shadow-red-100 transition-all active:scale-95 disabled:bg-slate-200 disabled:shadow-none"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-3">
                  <svg className="w-5 h-5 animate-spin" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
                  </svg>
                  AI is generating your plan...
                </span>
              ) : (
                <span className="flex items-center justify-center gap-2">
                  Generate My Nutrition Plan
                  <ChevronRight size={18} className="transition-transform group-hover:translate-x-1" />
                </span>
              )}
            </button>
          </form>
        </div>

        {!dietPlan && (
          <div className="min-h-[300px] bg-[#F8FAFC] border-2 border-dashed border-slate-200 rounded-[3rem] flex flex-col items-center justify-center p-12 text-center">
            <div className="flex items-center justify-center w-20 h-20 mb-6 bg-white shadow-sm rounded-3xl">
              <Utensils className="text-slate-300" size={32} />
            </div>
            <h3 className="mb-2 text-xl font-black tracking-tighter uppercase text-slate-400">
              Awaiting Parameters
            </h3>
            <p className="max-w-xs text-sm font-medium leading-relaxed text-slate-400">
              Fill in your biometric profile above and click Generate to receive
              your personalized heart-healthy nutrition plan.
            </p>
          </div>
        )}

        {dietPlan && (
          <div className="space-y-8 duration-700 animate-in fade-in slide-in-from-bottom-4">

            <div className="bg-red-600 rounded-[2rem] p-8 flex flex-col md:flex-row items-center justify-between gap-4">
              <div>
                <p className="text-[10px] font-black text-red-200 uppercase tracking-[0.4em] mb-1">
                  Daily Target
                </p>
                <h3 className="text-4xl font-black tracking-tighter text-white">
                  {dietPlan.calories}
                </h3>
              </div>
              <div className="text-sm font-bold tracking-widest text-center text-red-200 uppercase md:text-right">
                Personalized for your<br />
                <span className="text-white">{activityLevel} lifestyle · {weight}kg · Age {age}</span>
              </div>
            </div>

            <div>
              <p className="text-[10px] font-black text-red-600 uppercase tracking-[0.4em] mb-6 ml-2">
                Daily Meal Schedule
              </p>
              <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">
                {meals.map((meal, i) => (
                  <div
                    key={i}
                    className={`p-8 rounded-[2.5rem] border transition-all hover:shadow-lg ${
                      meal.dark
                        ? "bg-slate-900 border-slate-800"
                        : "bg-white border-slate-100 shadow-sm"
                    }`}
                  >
                    <div className="flex items-center justify-between mb-4">
                      <span className={`text-[9px] font-black uppercase tracking-widest ${meal.dark ? "text-red-400" : "text-red-600"}`}>
                        {meal.sublabel}
                      </span>
                      <div className={`p-2 rounded-xl ${meal.dark ? "bg-slate-800 text-red-400" : "bg-slate-50 text-slate-400"}`}>
                        {meal.icon}
                      </div>
                    </div>
                    <h4 className={`text-xl font-black uppercase tracking-tighter mb-3 ${meal.dark ? "text-white" : "text-slate-800"}`}>
                      {meal.label}
                    </h4>
                    <p className={`text-sm font-medium leading-relaxed ${meal.dark ? "text-slate-400" : "text-slate-500"}`}>
                      {meal.data}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">

              <div className="bg-white border border-slate-100 rounded-[2.5rem] p-8 shadow-sm">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 bg-green-50 rounded-xl">
                    <CheckCircle size={20} className="text-green-600" />
                  </div>
                  <h4 className="text-lg font-black tracking-tight uppercase text-slate-800">
                    Nutrition Tips
                  </h4>
                </div>
                <ul className="space-y-3">
                  {dietPlan.tips?.map((tip, i) => (
                    <li key={i} className="flex items-start gap-3">
                      <span className="flex-shrink-0 w-2 h-2 mt-1 bg-green-500 rounded-full" />
                      <p className="text-sm font-medium leading-relaxed text-slate-500">{tip}</p>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="bg-white border border-slate-100 rounded-[2.5rem] p-8 shadow-sm">
                <div className="flex items-center gap-3 mb-6">
                  <div className="p-2 bg-red-50 rounded-xl">
                    <AlertTriangle size={20} className="text-red-600" />
                  </div>
                  <h4 className="text-lg font-black tracking-tight uppercase text-slate-800">
                    Foods to Avoid
                  </h4>
                </div>
                <ul className="space-y-3">
                  {dietPlan.avoid?.map((item, i) => (
                    <li key={i} className="flex items-start gap-3">
                      <span className="flex-shrink-0 w-2 h-2 mt-1 bg-red-500 rounded-full" />
                      <p className="text-sm font-medium leading-relaxed text-slate-500">{item}</p>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div className="bg-slate-50 border border-slate-100 rounded-[2rem] p-6 flex items-start gap-4">
              <AlertTriangle size={18} className="text-slate-400 flex-shrink-0 mt-0.5" />
              <p className="text-xs font-medium leading-relaxed text-slate-400">
                This nutrition plan is AI-generated based on your provided metrics and is intended
                for informational purposes only. It does not constitute medical advice. Please
                consult a licensed dietitian or healthcare provider before making significant
                dietary changes, especially if you have pre-existing medical conditions.
              </p>
            </div>

          </div>
        )}
      </div>

      <div className="mt-20 text-center">
        <p className="text-[10px] font-black text-slate-300 uppercase tracking-[0.5em]">
          HeartFlow Nutrition Engine — Powered by Claude AI
        </p>
      </div>
    </div>
  );
};

export default Nutrition;
